site_name: 使用 Flutter 打造語音助理
site_url: https://zonble.github.io/flutter_voice_assistant
repo_url: https://github.com/zonble/flutter_voice_assistant
repo_name: zonble/flutter_voice_assistant
copyright: 2024 and onwards © Weizhong Yang a.k.a zonble
theme:
  name: material
  language: "zh-TW"
  # custom_dir: custom_theme/
  palette:
    - scheme: default
      primary: white
      accent: pink

      toggle:
        name: Switch to light mode
        icon: material/weather-sunny
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        name: Switch to dark mode
        icon: material/weather-night
  font:
    text: Lato
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.instant

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - footnotes

plugins:
  # - social:
  #     cards_font: Noto Sans TC
  - search
  - with-pdf:
      copyright: 2024 © 楊維中 a.k.a zonble
      author: 楊維中 a.k.a zonble
      cover_subtitle: 以 Gemini 為基礎的語音助理
      toc_title: 目錄
      output_path: flutter_voice_assistant.pdf
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
      puml_keyword: puml
      verify_ssl: true

extra_css:
  - css/extra.css
  - css/pdf-print.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zonble
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zonble
  search:
    language: "jp"

nav:
  - "index.md"
  - "chatbot_vs_assistant.md"
  - "components.md"
  - "packages.md"
  - "nlg_nlg_gemini.md"
  - "asr_tts_engine.md"
  - "vui_flow_design.md"
  - "vui_flow_impl.md"
  - "dialog_engine.md"
  - "confirm_cancel.md"
  - "challenges.md"
  - "next_steps.md"
  - "PDF 版本": flutter_voice_assistant.pdf
