site_name: 使用 Flutter 打造語音助理
site_url: https://zonble.github.io/flutter_voice_assistant/
repo_url: https://github.com/zonble/flutter_voice_assistant
repo_name: zonble/flutter_voice_assistant
copyright: 2024 and onwards © Weizhong Yang a.k.a zonble
theme:
  name: material
  language: "zh-TW"
  # custom_dir: custom_theme/
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        name: Switch to light mode
        icon: material/weather-sunny
    - scheme: slate
      primary: blue grey
      # accent: pink
      toggle:
        name: Switch to dark mode
        icon: material/weather-night
  font:
    text: Lato
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.instant

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - footnotes

plugins:
  - search
  # - social:
  #     cards_font: Noto Sans TC
  # - with-pdf:
  #     copyright: 2024 © 楊維中 a.k.a zonble
  #     author: 楊維中 a.k.a zonble
  #     cover_subtitle: 以 Gemini 為基礎的語音助理
  #     toc_title: 目錄
  #     output_path: flutter_voice_assistant.pdf
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
      puml_keyword: puml
      verify_ssl: true

nav:
  - "index.md"
  - "chatbot_vs_assistant.md"
  - "components.md"
  - "packages.md"
  - "nlg_nlg_gemini.md"
  - "asr_tts_engine.md"
  - "vui_flow_design.md"
  - "vui_flow_impl.md"
  - "dialog_engine.md"
  - "challenges.md"
  - "next_steps.md"
